### ISSUE TITLE
Developing AutoKey

### ISSUE THREAD

**Issue by josephj11** [ten0s/autokey#1]
Hi. Do you have any further plans to work on AutoKey?

We are looking for someone who can help maintain the project as the original developer has "retired". 

This is a totally informal request with no commitment involved. Anything you could do would be appreciated.

Joe

**Comment by ten0s** [comment]
Actually, I never worked on AutoKey and this repo is just my configs. 

Unfortunately, I don't have any spare time to dedicate to AutoKey.

**Comment by josephj11** [comment]
Thanks for getting back to me.

**Comment by gggtest** [comment]
There is someone who is maintaining a python3 port of autokey. https://github.com/guoci/autokey-py3

**Comment by winterlaite** [comment]
Thank you so much for your configs. I was unable to get any Autokey version to work on Linux Mint 17.1. Now it works! I hope the people at https://github.com/guoci/autokey-py3 will take note.
What a relief!
